### PR TITLE
Sources content concat

### PR DESCRIPTION
**Pull request by morganpackard**
Looks like I introduce some line ending issues to two of the .map files. Let me know if that's an issue and I'll fix.

### CODE REVIEW

**Comment by morganpackard** [comment]
Hi there. Following up on this. I'd love to get this merged in. Looks like there are some linter issues. If I sort those out do I have a reasonable chance of having this merged in?

**Comment by vasa-c** [comment]
@morganpackard, ok, fix it, please: https://travis-ci.org/axypro/sourcemap/jobs/197478012

**Comment by morganpackard** [comment]
I ran `phpcbf` and it do some (maybe) weird stuff to comments in `SourceMap.php`. https://github.com/axypro/sourcemap/pull/4/files?diff=unified#diff-618d65397dccaadae4585ee718730007R198 Let me know if you'd like to keep those formatting changes to comments or if I should revert all the changes except the lines I touched.

**Comment by vasa-c** [comment]
@morganpackard, hm.., this is realy weird :)
Revert comments, please.

**Comment by vasa-c** [comment]
Okey, thanks.

**Comment by morganpackard** [comment]
Thank you!

**Pull request merged**
